name: Build Azuriom egg docker image
run-name: ${{ github.actor }} is building azuriom-egg Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
jobs:
  Docker-Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo "Building branch ${{ github.ref }} for ${{ github.repository }} triggered by a ${{ github.event_name }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/mlhnono68/azuriom-egg
      - name: Build an egg pre-configured that docker image
        env:
          DOCKER_TAG: ${{ steps.meta.outputs.tags }}
        run: |
          env
          mkdir -p build
          cat egg-azuriom.json | jq '.docker_images = {"'$DOCKER_TAG'": "'$DOCKER_TAG'"}' > build/egg-azuriom.json
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: egg-azuriom
          path: |
            build/egg-azuriom.json
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
