name: Build Azuriom egg docker image
run-name: ${{ github.actor }} is building azuriom-egg Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
jobs:
  Docker-Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo "Building branch ${{ github.ref }} for ${{ github.repository }} triggered by a ${{ github.event_name }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/mlhnono68/azuriom-egg
      - name: Build an egg pre-configured that docker image
        env:
          DOCKER_TAG: ${{ steps.meta.outputs.tags }}
        run: |
          echo $DOCKER_TAG
          mkdir -p build
          cat egg-azuriom.json | jq '.docker_images = {}' > build/egg-azuriom.json 
          echo "$DOCKER_TAG" | while IFS= read -r UNIQUE_TAG ; do
            echo "Adding tag $UNIQUE_TAG"
            cat <<< $(jq '.docker_images += {"'$UNIQUE_TAG'": "'$UNIQUE_TAG'"}' build/egg-azuriom.json ) > build/egg-azuriom.json
          done
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: egg-azuriom
          path: |
            build/egg-azuriom.json
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  Publish-Release:
    runs-on: ubuntu-latest
    needs: Docker-Build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            build/egg-azuriom.json